---
title: "Nonhuman Primate Colony Management Test of a Cross-sectional Sampling Timer"
author: "R. Mark Sharp"
date: "`r Sys.Date()`"
output:
  bookdown::pdf_document2:
    extra_dependencies: ["float"]
  bookdown::html_document2: default
header-includes:
  - \usepackage{caption}
vignette: >
  %\VignetteIndexEntry{Nonhuman Primate Colony Management Test of a Cross-sectional Sampling Timer}
  %\usepackage[UTF-8]{inputenc}
  %\VignetteEngine{knitr::rmarkdown_notangle}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, fig.pos = 'H')
library(crosssectiontimer)
library(ggplot2)
library(kableExtra)
library(magrittr)
library(rmsutilityr)
library(stringi)
library(here)
here::i_am("vignettes/cross_sectional_timing_colony.Rmd") # needs to be in right
                                                        # directory
```
```{r customization}
source(
  system.file("extdata",
              "colony_customization.R",
              package = "crosssectiontimer", lib.loc = NULL,
              mustWork = FALSE))

```

```{r child = here("vignettes/components/_body_of_cross_sectional_timing_vignette.Rmd"), ref = "body"}

```
