---
title: "crossectiontime Package Contents"
author: "R. Mark Sharp"
date: "`r Sys.Date()`"
output:
  - rmarkdown::pdf_document
  - rmarkdown::latex_document
  - rmarkdown::html_document
  - rmarkdown::word_document
  
vignette: >
  %\VignetteIndexEntry{crossectiontime Package Contents}
  %\usepackage[UTF-8]{inputenc}
  %\VignetteEngine{knitr::knitr}
---

## Package Contents

Momentary time sampling (MTS) is a time-on-task 
estimation method that samples defined behaviours in the exact 
instant that you’re taking data. 
This package presents MTS^[Identified as Instantaneous, Pinpoint, 
Momentary, and Scan Sampling in animal and human behavior research. Momentary
Time Sampling dominates in the human literature.] in two parallel vignettes 
that use different value streams to illustrate the generality of the 
methodology. 
Each vignette describes the strengths of MTS over two
common longitudinal time collection methods: (1) time duration between 
milestones and (2) time logging.

The two vignettes contain topic specific simulations that illustrate the 
structure, simplicity,
accuracy, and precision of the cross-sectional time-on-task estimation method.
Three levels of sampling demonstrate the ease and relatively low impact that 
any need for increased precision would impose on the sampled population.
A discussion of appropriately identifying what activities to time and how the 
data could be collected is included.

Interested parties can use the two vignettes as examples to guide
simulating their own value streams. 
Further customization of the simulation can facilitate the
timing study design for the value streams of interest. 

This package contains all R functions used to create this document including
the simulation software. The two vignettes share almost all code and text.
Their individual attributes are provided by their separate parent documents,
the value stream's defined activities, and an R script that contains the 
directives of how the simulation is to be run and what value stream to examine.
The parent documents 
differ by three lines: the first is the title, the second is the name of 
the file, and the third is the name of the customization R code script which
is 18 lines long. 

Full documentation is at 
[https://rmsharp.github.io/crosssectiontimer/](
https://rmsharp.github.io/crosssectiontimer/)
